In [1]:
import numpy as np

In [2]:
x=np.array([2,5,9])

y=np.array([6,4,8])

In [3]:
x+y

array([ 8,  9, 17])

In [4]:
x*y

array([12, 20, 72])

In [5]:
x/y

array([0.33333333, 1.25      , 1.125     ])

In [6]:
x%y

array([2, 1, 1], dtype=int32)

In [7]:
x%2

array([0, 1, 1], dtype=int32)

In [8]:
x>20

array([False, False, False])

In [9]:
x<29

array([ True,  True,  True])

In [10]:
y**4

array([1296,  256, 4096], dtype=int32)

In [11]:
x

array([2, 5, 9])

In [12]:
x+=3

In [13]:
x

array([ 5,  8, 12])

In [14]:
y

array([6, 4, 8])

In [15]:
y*=2

In [16]:
y

array([12,  8, 16])

In [17]:
#unary operations

In [18]:
marks=np.array([78,98,65,69])

In [20]:
marks.sum()

310

In [22]:
marks.min()

65

In [23]:
marks.max()

98

In [26]:
marks.mean()

77.5

In [31]:
odds=np.arange(1,25,2).reshape(3,4)

In [32]:
odds

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [33]:
odds.shape

(3, 4)

In [35]:
odds.sum(axis=0)

array([27, 33, 39, 45])

In [36]:
odds.sum(axis=1)

array([16, 48, 80])

In [37]:
sachinscores=np.array([70,34,55,9,20,99,200,30,45,90])

In [39]:
print(np.mean(sachinscores))

65.2


In [40]:
np.median(sachinscores)

50.0